spring.application.name=expense-tracker

# Database config
spring.datasource.url=jdbc:h2:mem:expensetracker
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driver-class-name=org.h2.Driver

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Conf
app.jwt.secret=9a3b6f8a4c1d2e5f7a0b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f
app.jwt.expiration-ms=86400000

# server port
server.port=8081
